# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'joybox'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'amaizing-game'
  app.interface_orientations = [:landscape_left]
  app.deployment_target = '6.0'
end
